## Задание 1. Создание и изменение массивов

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9.
Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [3]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
A=A*2
for i in range(3):
    for j in range(3):
        if (A[i][j]>10):
            A[i][j]=0
A

array([[ 2,  4,  6],
       [ 8, 10,  0],
       [ 0,  0,  0]])

## Задание 2. Работа с булевыми масками

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.

In [190]:
A = np.random.randint(1, 101, size=(20))
print("Исходный массив: ",A)
print("Числа, которые делятся на 5 без остатка:")
for i in range(20):
    if (A[i]%5==0):
        print(A[i])
        A[i]=-1
print("Массив, в котором элементы, которые делятся на 5 без остатка, заменены на -1: ",A)


Исходный массив:  [18  6 22 88  3 50 42 15 94 47 67 75 19 40 72 78 59 91 32 80]
Числа, которые делятся на 5 без остатка:
50
15
75
40
80
Массив, в котором элементы, которые делятся на 5 без остатка, заменены на -1:  [18  6 22 88  3 -1 42 -1 94 47 67 -1 19 -1 72 78 59 91 32 -1]


## Задание 3. Объединение и разбиение массивов.

Создайте два массива NumPy размером 1×5, заполненные случайными числамиот 0 до 50.

    • Объедините эти массивы в один двумерный массив (по строкам).
    • Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

Выведите все промежуточные и итоговые результаты

In [234]:
A = np.random.randint(0,51, size=(1,5))
B = np.random.randint(0,51, size=(1,5))
print("Массивы 1x5, заполненные случайными числами от 0 до 50:")
print("А =",A);print("B =", B)
matrix = np.vstack((A,B))
print("Массивы А и В, обьединенные в один двумерный массив: ")
print(matrix)
A_new, B_new = np.vsplit(matrix, 2)
print("Двумерный массив, который был разделен обратно на два массива: ")
print("А =",A_new);print("B =", B_new)

Массивы 1x5, заполненные случайными числами от 0 до 50:
А = [[25 19 42 35 15]]
B = [[ 8  7 14 32 35]]
Массивы А и В, обьединенные в один двумерный массив: 
[[25 19 42 35 15]
 [ 8  7 14 32 35]]
Двумерный массив, который был разделен обратно на два массива: 
А = [[25 19 42 35 15]]
B = [[ 8  7 14 32 35]]


## Задание 4. Генерация и работа с линейными последовательностями

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты.

In [25]:
A = np.random.uniform(-10, 10, 50)
C = np.sum(A)
print("Массив из 50 чисел, равномерно распределенных от -10 до 10:\n", A)
print("Сумма всех элементов массива: ", C)
B = np.sum(A[A>0])
print("Сумма всех положительных элементов массива: ", B)
D = np.sum(A[A<0])
print("Сумма всех отрицательных элементов массива: ", D)

Массив из 50 чисел, равномерно распределенных от -10 до 10:
 [-3.04808618  5.77730068  0.73807768 -8.05731552  1.60705552  5.79984385
 -5.92565126  9.61903352  5.26405655 -4.950066    4.72879139 -1.44237931
  0.80228986  9.57082972  8.06686139  5.49478119  2.69195975 -8.6959409
 -9.3968371  -4.50666585 -1.94557818 -9.56312302  9.96547389 -4.73382486
  4.73850507  3.51775598 -7.92803748 -7.59597257 -0.97320504 -9.02104322
  1.79743826  2.32388716  8.85228084 -9.57510468 -2.56073903 -6.21598143
  2.41916251  3.55261564 -2.34903775  3.13052564  5.42738325 -4.55233852
 -3.12811804 -7.55588191  5.19800276  7.79417337  2.88497311 -2.07516092
  5.50483474  3.59402245]
Сумма всех элементов массива:  5.0658269970045
Сумма всех положительных элементов массива:  130.86191576180937
Сумма всех отрицательных элементов массива:  -125.7960887648049


## Задание 5. Работа с диагональными и единичными матрицами

Создайте:

    • Единичную матрицу размером 4х4.
    • Диагональную матрицу размером 4х4 с диагональными элементами (5,10,15,20), не используя циклы.

Найдите сумму всех элементов каждой из этих матриц и сравните результаты

In [314]:
A = np.eye(4)
print("Единичная матрица размером 4 порядка:\n",A)
B = np.diag([5, 10, 15, 20])
print("Диагональная матрица 4 порядка с диагональными элементами (5,10,15,20):\n", B)
k = np.sum(A)
k1 = np.sum(B)
print("Сумма всех элементов единичной матрицы:",k)
print("Сумма всех элементов диагональной матрицы:",k1)

Единичная матрица размером 4 порядка:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица 4 порядка с диагональными элементами (5,10,15,20):
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма всех элементов единичной матрицы: 4.0
Сумма всех элементов диагональной матрицы: 50


## Задание 6. Создание и базовые операции с матрицами

Создайте две квадратные матрицы NumPy размером 3х3, заполненые случайными целыми числами от 1 до 20. Вычислите и выведите:

    • Их сумму
    • Их разность
    • Их поэлементное произведение

In [356]:
A = np.random.randint(1,21, size=(3,3))
B = np.random.randint(1,21, size=(3,3))
print("A = \n",A)
print("B = \n",B)
C = A + B
print("A + B =\n",C)
D = A - B
print("A - B =\n",D)
E = A*B
print("A * B (поэлементное произведение) =\n",E)

A = 
 [[ 8 15 16]
 [ 6 12  9]
 [16 17 14]]
B = 
 [[ 1 13 14]
 [ 2  8 11]
 [19 18 17]]
A + B =
 [[ 9 28 30]
 [ 8 20 20]
 [35 35 31]]
A - B =
 [[ 7  2  2]
 [ 4  4 -2]
 [-3 -1 -3]]
A * B (поэлементное произведение) =
 [[  8 195 224]
 [ 12  96  99]
 [304 306 238]]


## Задание 7. Умножение матриц

Создайте две матрицы NumPy:

    • Первую размером 2х3, заполненную случайными числами от 1 до 10.
    • Вторую размеров 3х2, заполненную случайными числами от 1 до 10.

Выполните матричное умножение и выведите результат.

In [33]:
A = np.random.randint(1,11, size=(2,3))
B = np.random.randint(1,11, size=(3,2))
print("A = \n",A)
print("B = \n",B)
C = np.dot(A,B)
G = A@B
print("Произведение матрицы A на матрицу B с помощью dot:\n",C)
print("Произведение матрицы A на матрицу B с помощью @:\n",G)

A = 
 [[ 3  1 10]
 [ 4  5  8]]
B = 
 [[ 4  3]
 [ 2 10]
 [ 3  8]]
Произведение матрицы A на матрицу B с помощью dot:
 [[ 44  99]
 [ 50 126]]
Произведение матрицы A на матрицу B с помощью @:
 [[ 44  99]
 [ 50 126]]


## Задание 8. Определитель и обратная матрица

Создайте случайную квадратную матрицу 3х3. Найдите и выведите:

    • Определитель этой матрицы
    • Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)

Используйте функции np.linalg.det и np.linalg.inv

In [469]:
A = np.random.rand(3, 3)
print("Матрица А =\n",A)
C = np.linalg.det(A)
print("det A = ", C)
D = np.linalg.inv(A)
if (C != 0):
    print("A⁻¹ = \n", D)
else:
    print("det A = 0, обратной матрицы не существует!")


Матрица А =
 [[0.50650186 0.62886753 0.07887878]
 [0.20213945 0.65439707 0.82874358]
 [0.77868256 0.71258994 0.17992485]]
det A =  0.11464172628121103
A⁻¹ = 
 [[-4.12425788 -0.49668365  4.09582006]
 [ 5.31183787  0.25916168 -3.52241429]
 [-3.18841194  1.12315165  1.78237372]]


## Задание 9. Транспонирование и след матрицы

Создайте матрицу NumPy размером 4х4, содержащую случайные целые числа от 1 до 50. Выведите:

    • Исходную матрицу
    • Транспонированную матрицу
    • След матрицы (сумму элементов на главной диагонали)

Используйте np.trace для нахождения следа.

In [486]:
A = np.random.randint(1,51, size=(4,4))
print("Исходная матрица: \n",A)
print("Транспонированная матрица: \n", np.transpose(A))
print("След матрицы: ", np.trace(A))

Исходная матрица: 
 [[47  5  3  6]
 [ 9 50 32 30]
 [41 46  4  7]
 [29 20 15 44]]
Транспонированная матрица: 
 [[47  9 41 29]
 [ 5 50 46 20]
 [ 3 32  4 15]
 [ 6 30  7 44]]
След матрицы:  145


## Задание 10. Системы линейных уравнений 

Решите систему линейных уравнений вида: 
$
\begin{cases}
2x + 3y - z = 5 \\
4x - y + 2x = 6 \\
-3x + 5y + 4z = -2
\end{cases}
$

Используйте матричное представление AX = B, где А - матрица коэффициентов, х - вектор неизвестных, В - вектор правой части. Решите систему с помощью np.linalg.solve и выведите результат

In [525]:
A = np.array([[2,3,-1],
             [4,-1,2],
             [-3,5,4]])
B = np.array([[5],[6],[-2]])
print("Ответ:\n",np.linalg.solve(A,B))

Ответ:
 [[1.63963964]
 [0.57657658]
 [0.00900901]]


## Индивидуальное задание.

Задание предусматривает построение СЛУ. Решите полученную СУ с использованием библиотеки NumPy. <br>Для решения системы используйте **метод Крамера** и **матричный метод**. Сравните полученные результаты, с результатами, полученными с помощью **np.linalg.solve**.

**Вариант 12**.<br>
На концерт продано 500 билетов трех категорий: cтандартные, премиум и VIP.<br>
Билеты премиум стоят в 1.5 раза дороже стандартных, а VIP — в 2 раза дороже премиум.<br>
Общий доход от продажи составил 600 000 рублей.<br>
Сколько билетов каждого типа было продано, если известно, что стандартных билетов было на 100 больше, чем премиум?

#### upd: т.к у нас не указана цена стандартного билета, то примем его значение за 1000

Получим систему уравнений:
$
\begin{cases}
s + 1,5p + 3v = 600 \\
s + p + v = 500 \\
s - p = 100
\end{cases}
$

In [47]:
A = np.array([[1,1.5,3],
             [1,1,1],
             [1,-1,0]])
B = np.array([[600],
              [500],
              [100]])
G = np.linalg.inv(A)
matr = G@B
numpy = np.linalg.solve(A,B)
print("Ответ к СЛУ с помощью np.linalg.solve:\n",numpy)
print("Ответ к СЛУ с помощью матричного метода:\n",matr)
det = np.linalg.det(A)
s1 = np.array([[600,1.5,3],
              [500,1,1],
              [100,-1,0]])
p1 = np.array([[1,600,3],
             [1,500,1],
             [1,100,0]])
v1 = np.array([[1,1.5,600],
             [1,1,500],
             [1,-1,100]])
dets = np.linalg.det(s1)
detp = np.linalg.det(p1)
detv = np.linalg.det(v1)
s = dets/det
p = detp/det
v = detv/det
kramer = np.array([[s],
              [p],
              [v]])
print("Ответ к СЛУ с помощью метода Крамера:\n", kramer)

Ответ к СЛУ с помощью np.linalg.solve:
 [[ 3.00000000e+02]
 [ 2.00000000e+02]
 [-3.96508223e-15]]
Ответ к СЛУ с помощью матричного метода:
 [[3.0000000e+02]
 [2.0000000e+02]
 [1.0658141e-14]]
Ответ к СЛУ с помощью метода Крамера:
 [[ 3.00000000e+02]
 [ 2.00000000e+02]
 [-3.96508223e-15]]
