# Задания практической работы

### 1. Создание и изменение массивов.
Создайте массив NumPy  размеров 3x3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [3]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
A=A*2
A[A>10]=0
print("Итоговый массив:")
print(A)

Итоговый массив:
[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


### 2. Работа с булевыми масками.
Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.


In [6]:
import numpy as np
A = np.random.randint(1, 101, size=20)
print("Исходный массив:")
print(A)
print("Все элементы, которые делятся на 5 без остатка:")
B = A[A % 5 == 0]
print(B)
print("Заменил все элементы, которые делятся на 5 без остатка, на -1:")
A[A%5==0]=-1
print(A)

Исходный массив:
[ 29  16 100  55   8  10  78  22   9   8  71  54  27  41  58  43  95  49
  88  66]
Все элементы, которые делятся на 5 без остатка:
[100  55  10  95]
Заменил все элементы, которые делятся на 5 без остатка, на -1:
[29 16 -1 -1  8 -1 78 22  9  8 71 54 27 41 58 43 -1 49 88 66]


### 3. Объдинение и разбиение массивов.
Создайте два массива NumPy размером 1х5, заполненные случайными числами от 0 до 50.
- Объедините эти массивы в один двумерный массив (по строкам)
- Разделите полученный массив на два массива, каждый из которых содержит 5 элеменов

Выведите все промежуточные и итоговые результаты.

In [9]:
A = np.random.randint(0,51, size=(1,5))
B = np.random.randint(0,51, size=(1,5))
print("Массивы 1x5, заполненные случайными числами от 0 до 50:")
print("Первый массив:",A)
print("Второй массив:",B)
C = np.vstack((A, B))
print("Объединенный массив 2×5:")
print(C)
A_n, B_n = np.vsplit(C, 2)
print("Объедененный массив разделил на два массива, каждый из которых содержит 5 элементов:")
print("Первый объдиненный массив:", A_n)
print("Второй объдиненный массив:", B_n)

Массивы 1x5, заполненные случайными числами от 0 до 50:
Первый массив: [[ 9 25 32  2 16]]
Второй массив: [[30 43  9  5 32]]
Объединенный массив 2×5:
[[ 9 25 32  2 16]
 [30 43  9  5 32]]
Объедененный массив разделил на два массива, каждый из которых содержит 5 элементов:
Первый объдиненный массив: [[ 9 25 32  2 16]]
Второй объдиненный массив: [[30 43  9  5 32]]


### 4. Генерация и работа с линейными последовательностями.
Создайте массив из 50 чисел, равномерно распределеных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результат.

In [12]:
import numpy as np
A = np.linspace(-10, 10, 50)
print("Созданный массив:")
print(A)
B = np.sum(A)
print("Сумма всех элементов",B)
C = np.sum(A[A>0])
print("Сумма всех положительных элементов:",C)
D = np.sum(A[A<0])
print("Сумма всех отрицательных элементов:",D)



Созданный массив:
[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]
Сумма всех элементов 7.105427357601002e-15
Сумма всех положительных элементов: 127.55102040816328
Сумма всех отрицательных элементов: -127.55102040816327


### 5. Работа с диагональными и единичными матрицами.
Создайте:
- Единичную матрицу размером 4х4
- Диагональную матрицу размером 4х4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы)

Найдите сумму всех элементов каждой из этих матриц и сравните результат.

In [15]:
A = np.eye(4)
print("Единичная матрица 4х4:")
print(A)
B = np.diag([5, 10, 15, 20])
print("Диагональная матрица 4х4 с диагональными элементами [5,10,15,20]:")
print(B)
c = np.sum(A)
d = np.sum(B)
print("Сумма всех элементов единичной матрицы:",c)
print("Сумма всех элементов диагональной матрицы:",d)
     

Единичная матрица 4х4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица 4х4 с диагональными элементами [5,10,15,20]:
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма всех элементов единичной матрицы: 4.0
Сумма всех элементов диагональной матрицы: 50


### 6. Создание и базовые операции с матрицами.
Создайте две квадратные матрицы NumPy размером 3х3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:
- Их сумму
- Их разность
- Их поэлементное произведение 

In [18]:
A = np.random.randint(1,21, size=(3,3))
B = np.random.randint(1,21, size=(3,3))
print("Первая квадратная матрица 3х3:")
print(A)
print("Вторая квадратная матрица 3х3:")
print(B)
C = A + B
print("Сумма квадратных матриц:")
print(C)
D = A - B
print("Разность квадратных матриц:")
print(D)
E = A*B
print("Поэлементное произведение квадратных матриц:")
print(E)

Первая квадратная матрица 3х3:
[[ 4  2 12]
 [15  1  5]
 [ 2  9  5]]
Вторая квадратная матрица 3х3:
[[14 16 14]
 [16 19  7]
 [10  6  1]]
Сумма квадратных матриц:
[[18 18 26]
 [31 20 12]
 [12 15  6]]
Разность квадратных матриц:
[[-10 -14  -2]
 [ -1 -18  -2]
 [ -8   3   4]]
Поэлементное произведение квадратных матриц:
[[ 56  32 168]
 [240  19  35]
 [ 20  54   5]]


### 7. Умножение матриц. 
Создайте две матрицы NumPy:
- Первую размером 2х3, заполненную случайными числоами от 1 до 10
- Вторую размером 3х2, заполненную случайными числами от 1 до 10

Выполните матричное умножение (@ или np.dot) и выведите результат.

In [21]:
A = np.random.randint(1,11, size=(2,3))
B = np.random.randint(1,11, size=(3,2))
print("Первая матрица 2х3:")
print(A)
print("Вторая матрица 3х2:")
print(B)
C = np.dot(A,B)
D = A@B
print("Матричное умножение с помощью @:")
print(D)
print("Матричное умножение с помощью np.dot:")
print(C)

Первая матрица 2х3:
[[9 5 4]
 [1 6 9]]
Вторая матрица 3х2:
[[4 4]
 [8 1]
 [9 8]]
Матричное умножение с помощью @:
[[112  73]
 [133  82]]
Матричное умножение с помощью np.dot:
[[112  73]
 [133  82]]


### 8. Определитель и обратная матрица.
Создайте случайную квадратную матрицу 3х3. Найдите и выведите:
- Определитель этой матрицы
- Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)

Используйте функции np.linalg.det и np.linalg.inv

In [24]:
A = np.random.rand(3, 3)
print("Случайная квадратная матрица 3х3:")
print(A)
B = np.linalg.det(A)
print("Нашли определитель этой матрицы:")
print(B)
C = np.linalg.inv(A)
if (B != 0):
    print("Обратная матрица:")
    print(C)
else:
    print("Обратной матрицы не существует, она вырождена")

Случайная квадратная матрица 3х3:
[[0.83510291 0.91011896 0.17721545]
 [0.84975393 0.25813606 0.82513903]
 [0.93332399 0.91649608 0.77852506]]
Нашли определитель этой матрицы:
-0.26958033556881555
Обратная матрица:
[[ 2.05976186  2.02586419 -2.61602531]
 [-0.40272718 -1.79816196  1.9974991 ]
 [-1.99521809 -0.31184515  2.06916794]]


### 9. Транспонирование и след матрицы.
Создайте матрицу NumPy размером 4х4, содержащую случайные целые числа от 1 до 50. Выведите:
- Исходную матрицу
- Транспонированную матрицу
- След матрицы (сумму элементов на главной диагонали)

Используйте np.trace для нахождения следа.

In [27]:
A = np.random.randint(1,51, size=(4,4))
print("Матрица 4х4:")
print(A)
print("Транспонированная матрица:")
print(np.transpose(A))
print("След матрицы(сумму элементов на главной диагонали): ")
print(np.trace(A))

Матрица 4х4:
[[15 21 45  5]
 [44  4  1 49]
 [50 23 38 12]
 [40 20 25 39]]
Транспонированная матрица:
[[15 44 50 40]
 [21  4 23 20]
 [45  1 38 25]
 [ 5 49 12 39]]
След матрицы(сумму элементов на главной диагонали): 
96


### 10. Системы линейных уравнений.
Решите систему линейных уравнений вида:

$
\begin{cases}
2x + 3y - z = 5 \\
4x - y + 2x = 6 \\
-3x + 5y + 4z = -2
\end{cases}
$




Используйте матричное представление Ax = B , где A – матрица коэффициентов, х - вектор неизвестных, В - вектор провой части. Решите систему с помощью np.linalg.solve и выведите результат.

In [30]:
A = np.array([[2,3,-1],
             [4,-1,2],
             [-3,5,4]])
B = np.array([[5],[6],[-2]])
C = np.linalg.solve(A,B)
print("Результат:")
print(C)

Результат:
[[1.63963964]
 [0.57657658]
 [0.00900901]]


### 11. Индивидуальное задание.
Решите индивидуальное задание согласно варианту. Каждое задание предусматривает построение системы линейных уравнений. Решите полученную систему уравнений с использованием библиотеки NumPy. Для решения системы используйте метод Крамера и матричный метод. Сравните полученные результаты, с результатами, полученными с помощью np.linalg.solve.

**Распределение нагрузки на работников.** Три сотрудника должны выполнить 100 задач. Второй сотрудник должен выполнить на 10 задач больше, чем первый, а третий - в два раза больше, чем второй. Сколько задач получит каждый сотрудник?

Получим систему уравнений:
$
\begin{cases}
x + y + z = 100 \\
-x + y = 10 \\
-2y + z = 0
\end{cases}
$

In [79]:
import numpy as np

A = np.array([
    [1, 1, 1],    # x + y + z = 100
    [-1, 1, 0],    # -x + y = 10
    [0, -2, 1]     # -2y + z = 0
])
B = np.array([100, 10, 0])

n = np.linalg.solve(A, B)
print("Решение СЛУ с помощью np.linalg.solve:")
print(f"x = {n[0]:.0f}, y = {n[1]:.0f}, z = {n[2]:.0f}.")

G = np.linalg.inv(A)
m = G @ B
print("Решение СЛУ с помощью матричного метода:")
print(f"x = {m[0]:.0f}, y = {m[1]:.0f}, z = {m[2]:.0f}.")

det_A = np.linalg.det(A)

A_x = A.copy()
A_x[:, 0] = B
x = np.linalg.det(A_x) / det_A

A_y = A.copy()
A_y[:, 1] = B
y = np.linalg.det(A_y) / det_A

A_z = A.copy()
A_z[:, 2] = B
z = np.linalg.det(A_z) / det_A

k = np.array([x, y, z])
print("Решение СЛУ с помощью метода Крамера:")
print(f"x = {k[0]:.0f}, y = {k[1]:.0f}, z = {k[2]:.0f}.")

Решение СЛУ с помощью np.linalg.solve:
x = 18, y = 28, z = 55.
Решение СЛУ с помощью матричного метода:
x = 18, y = 28, z = 55.
Решение СЛУ с помощью метода Крамера:
x = 18, y = 28, z = 55.
